### ISSUE TITLE
Membership Matrix

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician#373]
This is a meta ticket to contain the discussions around our new membership editing interface, AKA [membership_matrix](https://github.com/everypolitician/membership_matrix).

Issues specifically about the UI should be added to the [membership_matrix issue tracker](https://github.com/everypolitician/membership_matrix/issues).
- [x] Build a UI for adding, editing and removing term memberships
- [ ] Add a server component that pushes updates from the UI into EveryPolitician https://github.com/everypolitician/membership_matrix/issues/9
- [ ] Use the data produced by the tool in EveryPolitician as the main source of truth for memberships - https://github.com/everypolitician/everypolitician-data/pull/7014

**Comment by chrismytton** [comment]
This is required to get Mzalendo working with EveryPolitician data.

**Comment by chrismytton** [comment]
I've just been thinking through what the next iteration of this will look like.

The initial version we built assumed that it would be pushing data to EveryPolitician via a pull request, but from past experience we've realised that this is probably the wrong way to solve this problem as it couples the membership matrix to the concept of pull request and the everypolitician-data repo.

Instead the membership matrix should expose the resulting memberships over an API, in the same way Gender Balance does. Then EveryPolitician can pull the data in as it does with all the other sources and combine it with other sources and create a pull request with the result.

### Datasource

Each instance of the membership matrix will be populated from multiple inputs. These inputs should simply be urls that return data in the appropriate format.

Ideally the datasource itself will live in a separate GitHub repository to the membership matrix so that the datasource configuration can be updated independently of the membership matrix.

#### Input types
- **Events** - these will usually appear on the x axis across the top of the matrix.
- **Posts or areas** - these will usually appear on the y axis down the left hand side of the matrix
- **People** - the MPs/Representatives/etc that hold the post/represent the area for a given event
- **Groups** - the parties/factions/etc that the person represents
- **Existing memberships** - Any existing combinations of the above 4 inputs, this might come from EveryPolitician or it might be stored in the membership matrix DB.

I propose something like the following for the datasource file:

``` yaml
---
datasources:
  - key: legislative_period_id
    source: https://prancing-horse-42.herokuapp.com/wikidata/riigikogu-terms.csv
    x_axis: true
  - key: area_id
    source: https://prancing-horse-42.herokuapp.com/mapit/estonia-areas.csv
    y_axis: true
  - key: person_id
    source: https://prancing-horse-42.herokuapp.com/google-sheets/estonia-people.csv
  - key: on_behalf_of_id
    source: https://prancing-horse-42.herokuapp.com/morph/tmtmtmtm/estonia-parties/all.csv
```

### Processing

The membership matrix will look fairly similar to how it does currently, but with the following changes:
- Memberships can't be deleted (i.e. they should be immutable)
- Add a button to end a membership - this will set and end date on the membership and create a new membership with a start date matching the previous memberships' end data.
- Add a button for changing party, as above this will explicitly end the old membership and create a new one for adding a new party.
- The data will be persisted to a local database. This can then be served up over the API to EveryPolitician.
- Probably move away from using Jekyll and instead have a Sinatra app which reads the datasources in and then generates an html interface for them and provides an API for the data. There will probably be a separate deploy of this app for each country that uses the membership matrix, then the datasource can be specified using a url in an environment variable.

### Output
- List of **memberships** in a format that EveryPolitician can consume, JSON or CSV format.
