### ISSUE TITLE
Add test for missing end-date on any term which is not the last one

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#465]
# Problem

We'd expect to have a date (even a partial date) for the end-date of any term for which we have a following term.

Recent work on Iran (adding a new term) showed we're not checking for this.

(Note: a good source for many end-of-term dates may be the [Inter-parliamentary Union's data](http://www.ipu.org/english/home.htm)

Originally ticketted as everypolitician/everypolitician-data#13603 (wrong repo)
# Proposed Solution

Check for non-empty end dates when there is a following term
# Acceptance Criteria

All terms that are not the most recent have an end data
# Not Required

None
# Prerequisites

None
# Related Issues

None
# Due Date

—
# Design?

No
# Text?

No
# Bloggable?

No

**Comment by tmtmtmtm** [comment]
> All terms that are not the most recent have an end data

Presumably adding a test for missing end dates will simply give us lots of errors, rather than magically giving us lots of data? ;)

Does that meant that this ticket is actually for ensuring we _have_ the end dates everywhere, or just that we get _notified_ when we don't?

**Comment by wfdd** [comment]
It sounds like something you could handle with [JSON schema](http://json-schema.org/examples.html) more generally, inheriting from Popolo and relaxing or restricting the schema as required:

``` yaml
# Lax schema
oneOf:
  - properties:
      classification:
        enum: ["legislative period"]
    required:
      - start_date
  ...

# Strict schema
oneOf:
  - properties:
      classification:
        enum: ["legislative period"]
    required:
      - start_date
      - end_date
  ...
```

Validation could be added as a build step, be part of the bot's summary of changes or be part of the test suite.  You could run all sorts of data integrity checks this way [1]:

``` yaml
email:
  not:
    pattern: mailto:
```

---

[1] Though not anything that might require a memory...
